### ISSUE TITLE
OSX executable missing file extension?

### ISSUE THREAD

**Issue by ideaprison** [mmcdole/sonagram#5]
I'm trying to install the OSX version of sonagram. 
Following the guide step #5, I tried running it through terminal first [/user/fluxcapacitor/sonarr/sonagram/sonagram-osx /user/fluxcapacitor/sonarr/sonagram/config.json]
but I get 'permission denied'

Skipping that step from the installation guide, and filling in the custom notifier in Sonarr's admin panel, I don't receive any notifications.

So either the release is missing a file extension (I tried .app the OS default) but does not make it work.

I am 100% certain my tokens are correct as they work for other apps like Couchpotato.

Thanks.

**Comment by ideaprison** [comment]
Aside from having to rename the file with .app at the end. Main problem was I had to set CHMOD to 755.

**Comment by mmcdole** [comment]
@ideaprison you shouldn't need to rename the file to `.app`.  It is simply an executable.  I'm guessing for security reasons the file doesn't return it's executable permission?  I may need to update the directions to indicate this possibility.

**Comment by ideaprison** [comment]
You're right it was merely the permissions problem, you could add that to the directions. I only extracted the archive and moved it into another folder. I suppose this doesn't happen all the time to who may be using your plugin.

Another question, is there a way to get the episode title? I see you did not list it. But Sonarr does provide it at the renaming function {Episode Title}
