### ISSUE TITLE
Synology binary?

### ISSUE THREAD

**Issue by schumi2004** [mmcdole/sonagram#6]
Can sonagram also run on a Synology NAS?

**Comment by mmcdole** [comment]
Can you try the linux 64 bit? 


https://www.faun.me/2015/02/17/cross-compiling-golang-applications-for-synology-1513

**Comment by schumi2004** [comment]
My Synology has ARM architecture so I doubt the linux 64 bit it will run. But maybe that link you gave can help me further. I'll try to cross-compile for ARm and see what happens.

**Comment by mmcdole** [comment]
Let me know if it works.  If it does I can try and include arm binaries

**Comment by schumi2004** [comment]
Well, it did compile but returns error when running:

admin@DS715:/volume1/@appstore/scripts/sonagram$ ./sonagram-arm
runtime: kernel page size (32768) is larger than runtime page size (4096)

**Comment by schumi2004** [comment]
Okay, my bad.
I shouldn't have followed this guide to get Go installed https://www.digitalocean.com/community/tutorials/how-to-install-go-1-6-on-ubuntu-16-04

But instead i should have done what Ubuntu told me and install it using sudo apt-get install golang-go
After that building using GOOS=linux GOARCH=arm go build create a proper binary.

admin@DS715:/volume1/@appstore/scripts/sonagram$ ./sonagram
2016/10/08 00:16:32 open config.json: no such file or directory

**Comment by mmcdole** [comment]
Looks good!  So you have gotten it to successfully fire then?

**Comment by schumi2004** [comment]
Not yet but since it asked for missing json I'm confident it works.

**Comment by schumi2004** [comment]
It seems to function but i'm unable to create chat_id. Going to do some reading on that but my issue seems to be resolved regarding binary for arm.
